CREATE TABLE LOCATION
(
    LOCATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(2) NOT NULL
);

CREATE TABLE POLICE_DEPARTMENT
(
    PD_ID INT AUTO_INCREMENT PRIMARY KEY,
    PD_NAME VARCHAR(100) NOT NULL,
    PD_CITY VARCHAR(100) NOT NULL,
    PD_STATE VARCHAR(50) NOT NULL
);

CREATE TABLE CRIME_TYPE
(
    CRIME_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY,
    CRIME_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PERPETRATOR
(
    PERP_ID INT AUTO_INCREMENT PRIMARY KEY,
    PERP_FNAME VARCHAR(50) NOT NULL,
    PERP_LNAME VARCHAR(50) NOT NULL,
    PERP_MNAME VARCHAR(50),
    PERP_DOB DATE NOT NULL
);

CREATE TABLE INCIDENT
(
    INCIDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    INCIDENT_DATE DATE NOT NULL,
    INCIDENT_SEVERITY VARCHAR(10) NOT NULL,
    LOCATION_ID INT NOT NULL,
    CRIME_TYPE_ID INT NOT NULL,
    PD_ID INT NOT NULL,

    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),
    FOREIGN KEY (CRIME_TYPE_ID) REFERENCES CRIME_TYPE(CRIME_TYPE_ID),
    FOREIGN KEY (PD_ID) REFERENCES POLICE_DEPARTMENT(PD_ID)
);

CREATE TABLE INCIDENT_PERP
(
    INCIDENT_ID INT NOT NULL,
    PERP_ID INT NOT NULL,

    PRIMARY KEY (INCIDENT_ID, PERP_ID),

    FOREIGN KEY (INCIDENT_ID) REFERENCES INCIDENT(INCIDENT_ID),
    FOREIGN KEY (PERP_ID) REFERENCES PERPETRATOR(PERP_ID)
);

CREATE TABLE INCIDENT_REPORT
(
    INCIDENT_ID INT PRIMARY KEY,
    FILE_DATE DATE NOT NULL,

    FOREIGN KEY (INCIDENT_ID) REFERENCES INCIDENT(INCIDENT_ID)
);

CREATE TABLE INCIDENT_UPDATE
(
    INCIDENT_ID INT NOT NULL,
    UPDATE_NUM INT NOT NULL,
    UPDATE_DATE DATE NOT NULL,

    PRIMARY KEY (INCIDENT_ID, UPDATE_NUM),

    FOREIGN KEY (INCIDENT_ID) REFERENCES INCIDENT(INCIDENT_ID)
);